name: Pipeline
on:
  push:
    branches: [main]
    paths: ["**.go", "go.mod", "go.sum"]
  pull_request:
    branches: [main]
    paths: ["**.go", "go.mod", "go.sum"]
  workflow_dispatch:

jobs:
  checks:
    name: 📋 Build and Test checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: 🏗️ Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: 🛠️ Build
        run: go build ./...

      - name: 🧪 Run Tests
        run: go test ./... --cover -coverprofile=reports/coverage.out
